files:
  - source: /src/main/resources/assets/accurateblockplacement/lang/en_US.json
    translation: /src/main/resources/assets/accurateblockplacement/lang/%locale_with_underscore%.json
commit_message: "[ci skip]"